### ISSUE TITLE
Bug: Lobby will transition into csf_intro even if the player is not in the elevator

### ISSUE THREAD

**Issue by The-Brickler** [Spekktrum-Studio/portal-system-failure-issue-tracker#12]
### Describe the bug

As soon as Vixie's end dialog is triggered, you are doomed to transition into the next map ready you want to or not.

### Issue Map

sp_a1_lobby

### To Reproduce

https://github.com/user-attachments/assets/02ab1387-3864-4305-9aa2-883f061a0069

**Comment by Rip-Rip-Rip** [comment]
Fixed
