### ISSUE TITLE
Bug: Visible untextured surface in csf_intro

### ISSUE THREAD

**Issue by The-Brickler** [Spekktrum-Studio/portal-system-failure-issue-tracker#13]
### Describe the bug

By looking at specific angles, it's possible to see untextured surfaces. It's easier with a cube

### Issue Map

sp_a1_csf_intro

### To Reproduce

https://github.com/user-attachments/assets/6ee57f18-bf23-4e02-87e4-e46c1cdfa4ab

**Comment by Rip-Rip-Rip** [comment]
Fixed
