### ISSUE TITLE
Bug: Cameras cannot be dropped down the pit :(

### ISSUE THREAD

**Issue by The-Brickler** [Spekktrum-Studio/portal-system-failure-issue-tracker#14]
### Describe the bug

When people see physics objects and a pit right next to them, most people will want to throw them down the pit but a clip brush prevents that.

### Issue Map

sp_a1_csf_intro

### To Reproduce

https://github.com/user-attachments/assets/dc93fb1b-465c-41de-b062-1e93f1e35f7e

**Comment by Rip-Rip-Rip** [comment]
Fixed, replaced the clip with a playerclip brush
