### ISSUE TITLE
Bug: Cubes in a vactube visibly pass through the wall

### ISSUE THREAD

**Issue by The-Brickler** [Spekktrum-Studio/portal-system-failure-issue-tracker#15]
### Describe the bug

The tube bends, but instead of following the curve, the cubes keep going straight through the wall

### Issue Map

sp_a1_csf_intro

### To Reproduce

https://github.com/user-attachments/assets/c62f488d-79d7-4336-a336-18070f8e6186

**Comment by Rip-Rip-Rip** [comment]
the spawning of this cube can also be seen quite obviously

just decided to remove it entirely
