### ISSUE TITLE
Bug: Z-fighting in the roof tiles

### ISSUE THREAD

**Issue by The-Brickler** [Spekktrum-Studio/portal-system-failure-issue-tracker#16]
### Describe the bug

In the missing tiles above the second chamber in csf_02, there is z-fighting

### Issue Map

sp_a1_csf_02

### To Reproduce

https://github.com/user-attachments/assets/ea29f29c-94ed-4aee-979d-8830b6847b06

**Comment by Rip-Rip-Rip** [comment]
Fixed :D

(Also added collision to the 3 square beam things next to it)
