### ISSUE TITLE
Bug: Softlock by switching cubes around

### ISSUE THREAD

**Issue by The-Brickler** [Spekktrum-Studio/portal-system-failure-issue-tracker#17]
### Describe the bug

In portalgun_intro, if you switch the cubes around, you can reenable the death fizzler after you've grabbed the portal gun, letting you trap yourself.

### Issue Map

sp_a1_portalgun_intro

### To Reproduce

(has to be a youtube video because it's too big)
https://youtu.be/pCQcCYsuROk

**Comment by Rip-Rip-Rip** [comment]
Fixed :D
