### ISSUE TITLE
Bug: Softlock due to portals being deleted too early.

### ISSUE THREAD

**Issue by The-Brickler** [Spekktrum-Studio/portal-system-failure-issue-tracker#18]
### Describe the bug

The portal should probably only close after you've passed through the exit door, but if you go to the exit door without a cube, the portal will close and you will be unable to get the cube.

### Issue Map

sp_a1_portalgun_intro

### To Reproduce

https://github.com/user-attachments/assets/6b10571b-3259-430f-8313-56321dbb1570

**Comment by Rip-Rip-Rip** [comment]
Fixed :D

**Comment by Badpoolinator** [comment]
> Fixed :D


i fixed this earlier, didn't find this issue though. did you pull the changes?

**Comment by Rip-Rip-Rip** [comment]
Yea I noticed this was fixed after checking for this issue lol
