### ISSUE TITLE
Subtitle issue in sp_a1_fizzler_gate

### ISSUE THREAD

**Issue by 216321** [Spekktrum-Studio/portal-system-failure-issue-tracker#2]
![bug](https://github.com/user-attachments/assets/cf2e5950-259f-4623-b4b2-0db6d9fdfa70)

**Comment by PRYZMwubs** [comment]
Fixed.

![Screenshot 2024-10-04 151427](https://github.com/user-attachments/assets/d4c0e5b6-839a-468b-b854-19cc2df6a442)
