### ISSUE TITLE
Bug: Unclipped framework in laser_intro

### ISSUE THREAD

**Issue by The-Brickler** [Spekktrum-Studio/portal-system-failure-issue-tracker#22]
### Describe the bug

A lot of the framework models have no clipping, allowing you to just walk through them.

### Issue Map

sp_a1_laser_intro

### To Reproduce

https://github.com/user-attachments/assets/d268748e-9e23-4761-a2aa-539d2487d4f6

https://github.com/user-attachments/assets/fed51007-f830-4f9f-95a4-3d713aaba583

**Comment by Rip-Rip-Rip** [comment]
Fixed :D
