### ISSUE TITLE
Bug: Kill trigger doesn't cover the whole pit

### ISSUE THREAD

**Issue by The-Brickler** [Spekktrum-Studio/portal-system-failure-issue-tracker#23]
### Describe the bug

If you jump in certain places, you can fall all the way down without dying.

### Issue Map

sp_a1_portalgun_upgrade

### To Reproduce

https://github.com/user-attachments/assets/5a079379-e8d6-4e52-ad80-09ebea2136fc

**Comment by Rip-Rip-Rip** [comment]
Fixed :D
