### ISSUE TITLE
Bug: By placing yourself, the cube, and your portals on the starting platform, the only way out is barely visible

### ISSUE THREAD

**Issue by The-Brickler** [Spekktrum-Studio/portal-system-failure-issue-tracker#24]
### Describe the bug

By getting into this situation, it is impossible to get out unless you notice the portal surface which can only be seen from certain positions or angles. There should probably be additional, more visible portal surfaces over there.

### Issue Map

sp_a1_portalgun_upgrade

### To Reproduce

https://github.com/user-attachments/assets/dba85571-300a-4069-9312-22da7aa010d2

**Comment by Rip-Rip-Rip** [comment]
Fixed, added a white panel over there

![image](https://github.com/user-attachments/assets/749c9b8b-ec7f-430b-834a-e0d8fa0a1c4b)
