### ISSUE TITLE
Bug: Floating wires in portalgun_upgrade

### ISSUE THREAD

**Issue by The-Brickler** [Spekktrum-Studio/portal-system-failure-issue-tracker#25]
### Describe the bug

There are wires that are not attached to anything

### Issue Map

sp_a1_portalgun_upgrade

### To Reproduce

https://github.com/user-attachments/assets/32372edd-357a-421e-9ec9-cb8fbff6be81

**Comment by Rip-Rip-Rip** [comment]
Fixed :D
