### ISSUE TITLE
Bug: Pit in portalgun_upgrade deletes cubes right in front of you

### ISSUE THREAD

**Issue by The-Brickler** [Spekktrum-Studio/portal-system-failure-issue-tracker#26]
### Describe the bug

The trigger deletes the cube as soon as it enters, which doesn't look good. It should either fizzle the cube, or just let the cube live.

### Issue Map

sp_a1_portalgun_upgrade

### To Reproduce

https://github.com/user-attachments/assets/b0338728-edf9-4424-872c-f20a81d4dfaf

**Comment by Rip-Rip-Rip** [comment]
Fixed :D
