### ISSUE TITLE
Bug: Floor clipping causes the floor to be very bumpy to walk on

### ISSUE THREAD

**Issue by The-Brickler** [Spekktrum-Studio/portal-system-failure-issue-tracker#27]
### Describe the bug

The base floor height is higher than the clip brush height so walking on the missing tiles causes screen jittering.

### Issue Map

sp_a1_portalgun_upgrade

### To Reproduce

https://github.com/user-attachments/assets/d81daa65-3067-4a9e-9ab4-a2b026740472

**Comment by Rip-Rip-Rip** [comment]
Fixed :D
