### ISSUE TITLE
Bug: Walking behind a panel traps you behind it forever

### ISSUE THREAD

**Issue by The-Brickler** [Spekktrum-Studio/portal-system-failure-issue-tracker#28]
### Describe the bug

When I walk behind the panel, for some reason it closes and you can't get back out

### Issue Map

sp_a1_portalgun_upgrade

### To Reproduce

https://github.com/user-attachments/assets/9788122f-d5fd-4d94-9b06-a5b29c3de015

**Comment by Alton-ion** [comment]
Yeah that was one of our trolls intended for the playtesters. Should be removed by the next update (probably).

**Comment by PRYZMwubs** [comment]
Correction: that is _not_ a troll, but an actual bug that we didn't get around to fix (or knew about.)

**Comment by Rip-Rip-Rip** [comment]
Removed the trigger to close the panel... so fixed..?

**Comment by Badpoolinator** [comment]
> Correction: that is _not_ a troll, but an actual bug that we didn't get around to fix (or knew about.)

There's no way that the trigger there to close the panel was a bug. That couldn't have been unintentionally placed.

**Comment by Rip-Rip-Rip** [comment]
There was literally an unconnected game_text entity named easter egg inside the area with the panel lolll

**Comment by Badpoolinator** [comment]
Even then that means we knew about it.
