### ISSUE TITLE
Bug: Unintended solution in barrier's 2nd chamber

### ISSUE THREAD

**Issue by The-Brickler** [Spekktrum-Studio/portal-system-failure-issue-tracker#30]
### Describe the bug

With a sharp laser angle, you can skip most of the test chamber

### Issue Map

sp_a1_barrier

### To Reproduce

https://github.com/user-attachments/assets/0747901a-e8fb-48a4-a259-3420f4045aa1

**Comment by Alton-ion** [comment]
Known bug. Will be fixed by the next update
