### ISSUE TITLE
Bug: There is no Chamber 12

### ISSUE THREAD

**Issue by systemfailurefan46** [Spekktrum-Studio/portal-system-failure-issue-tracker#4]
### Describe the bug

The map following Chamber 11 starts with Chamber 13.
![2766240_20241005012815_1](https://github.com/user-attachments/assets/6ff9b7be-c4b4-49ec-b916-f5ddfeacb093)
![2766240_20241005012829_1](https://github.com/user-attachments/assets/7b533a1a-13c2-40fa-9ec4-08ae8bcfbce8)

### Issue Map

sp_a1_laser_intro, sp_a1_portalgun_upgrade

### To Reproduce

1. Look at last sign in sp_a1_laser_intro
2. Look at first sign in sp_a1_portalgun_upgrade

**Comment by PRYZMwubs** [comment]
This isn't a bug, the map is just unfinished.
