### ISSUE TITLE
Bug: Slightly misaligned indicator lights in sp_a1_csf_02

### ISSUE THREAD

**Issue by Rip-Rip-Rip** [Spekktrum-Studio/portal-system-failure-issue-tracker#7]
### Describe the bug

![image](https://github.com/user-attachments/assets/a8287037-e154-4133-899e-9118bca1229b)

### Issue Map

sp_a1_csf_02

### To Reproduce

Observe.....

**Comment by PRYZMwubs** [comment]
Fixed.

![Screenshot 2024-10-04 155205](https://github.com/user-attachments/assets/86c1f453-0025-4ea5-aad7-33daf85fafe6)
