### ISSUE TITLE
Bug: Weird Collisions around fizzler emitter models

### ISSUE THREAD

**Issue by The-Brickler** [Spekktrum-Studio/portal-system-failure-issue-tracker#9]
### Describe the bug

A lot of the emitter models have weird messed up collisions and are creating invisible walls

### Issue Map

Appears in a lot of maps, but very noticeable on sp_a1_laser_intro

### To Reproduce

https://github.com/user-attachments/assets/7ffe6555-ec12-4e27-90fa-a689192df7c0

https://github.com/user-attachments/assets/2574bb97-057a-4a11-a40a-67d67e6e60ae

**Comment by Rip-Rip-Rip** [comment]
Turns out their bounding box is severly misaligned
![image](https://github.com/user-attachments/assets/ecfff101-ace1-456e-86c0-49b1335a080f)

Fixed inside the instance, will be updated across maps as they're recompiled
